'use client'

import { useState } from 'react'
import { Check, ChevronDown, ChevronRight, CreditCard, LockKeyhole, MessageCircle, LoaderCircle } from 'lucide-react'
import Link from 'next/link'
import { useAuth } from '@/components/auth'
import { Header } from '@/components/marketplace'
import { RequireAuth } from '@/components/require-auth'
import { createPackageOrder } from '@/lib/orders'
import { formatPrice, type Package, type Service } from '@/lib/services'

function OrderSummary({ service, pkg, expanded, onToggle }: { service: Service; pkg: Package; expanded: boolean; onToggle: () => void }) { return <aside className={`checkout-summary ${expanded ? 'summary-expanded' : ''}`}><button className="summary-mobile-toggle" onClick={onToggle}><span>Resumen de tu orden</span><strong>{formatPrice(pkg.price)}</strong><ChevronDown className={expanded ? 'rotated' : ''} /></button><div className="summary-content"><div className="summary-service"><img src={service.image} alt={service.title} /><div><strong>{service.title}</strong><span>{service.provider}</span></div></div><div className="summary-package"><div><span>Paquete elegido</span><strong>{pkg.name}</strong></div><span className="summary-time">{pkg.time} de entrega</span></div><ul className="summary-includes">{pkg.items.map(item => <li key={item}><Check /> {item}</li>)}</ul><div className="price-breakdown"><div><span>Subtotal</span><strong>{formatPrice(pkg.price)}</strong></div><div><span>Cargo de servicio</span><strong>$0</strong></div><div className="total-row"><span>Total</span><strong>{formatPrice(pkg.price)}</strong></div></div><div className="trust-list"><span><LockKeyhole /> Pago seguro</span><span><MessageCircle /> Soporte post-entrega</span></div></div></aside> }

function CheckoutForm({ service, pkg }: { service: Service; pkg: Package }) {
  const { user } = useAuth()
  const [loading, setLoading] = useState(false)
  const [orderId, setOrderId] = useState<string | null>(null)
  const [error, setError] = useState('')

  if (orderId) return <section className="success-state"><span className="success-icon"><Check /></span><h1>¡Pago confirmado!</h1><p>Tu orden #{orderId} fue creada, el proveedor la verá en breve.</p><Link className="primary-button wide-button" href="/ordenes">Ver mis órdenes <ChevronRight /></Link><Link className="secondary-button" href="/">Volver al inicio</Link></section>

  // RequireAuth garantiza sesión. La orden la crea la base (crear_orden_paquete) con el monto del paquete; pago simulado.
  return <form className="payment-form" onSubmit={async event => { event.preventDefault(); if (!user) return; setError(''); setLoading(true); const result = await createPackageOrder(pkg.id); setLoading(false); if (result.ok) setOrderId(result.shortId); else setError(result.error) }}>{error && <div className="payment-error" role="alert"><strong>{error}</strong></div>}<section className="form-section"><div className="section-kicker">1</div><div className="form-section-body"><h2>Datos de contacto</h2><p>Te enviaremos la confirmación de tu orden a estos datos.</p><div className="form-fields"><label>Nombre completo<input required defaultValue={user?.name} placeholder="Tu nombre" /></label><label>Email<input required type="email" defaultValue={user?.email} placeholder="nombre@email.com" /></label></div></div></section><section className="form-section"><div className="section-kicker">2</div><div className="form-section-body"><h2>Método de pago</h2><p>Ingresá los datos de tu tarjeta para completar la compra.</p><div className="payment-method"><CreditCard /><strong>Tarjeta de crédito o débito</strong><span>Visa · Mastercard</span></div><div className="form-fields"><label className="field-full">Número de tarjeta<input required inputMode="numeric" placeholder="0000 0000 0000 0000" /></label><label>Vencimiento<input required placeholder="MM / AA" /></label><label>CVV<input required inputMode="numeric" placeholder="123" /></label></div></div></section><label className="terms-check"><input required type="checkbox" /> <span>Acepto los <a href="#">términos y condiciones</a> de la compra.</span></label><button className="primary-button wide-button payment-submit" disabled={loading}>{loading ? <><LoaderCircle className="spinner" /> Procesando pago...</> : <>Confirmar y pagar <ChevronRight /></>}</button><p className="payment-note"><LockKeyhole /> Tu información está protegida y se procesa de forma segura.</p></form>
}

export function CheckoutView({ service, pkg }: { service: Service; pkg: Package }) { const [summaryOpen, setSummaryOpen] = useState(false); return <main className="checkout-page"><Header note={<span className="checkout-secure"><LockKeyhole /><span>Checkout seguro</span></span>} /><RequireAuth reason="comprar"><div className="checkout-container"><Link className="back-link" href={`/servicios/${service.id}`}>← Volver a la ficha de servicio</Link><div className="checkout-breadcrumb"><span>Ficha de servicio</span><ChevronRight /><strong>Checkout</strong></div><div className="checkout-grid"><div className="checkout-main"><div className="checkout-heading"><span className="eyebrow">RESUMEN Y PAGO</span><h1>Finalizá tu compra</h1><p>Estás a un paso de empezar tu proyecto con {service.provider}.</p></div><CheckoutForm service={service} pkg={pkg} /></div><OrderSummary service={service} pkg={pkg} expanded={summaryOpen} onToggle={() => setSummaryOpen(value => !value)} /></div></div></RequireAuth></main> }
